Create Schedule vaccine section
bildvitta/covid pull request #59
Opened 2021-03-09 13:43 UTC by RafaelM-DEv

2021-03-10 13:12 UTC, DouglasCalora requested changes

2021-03-10 13:12 UTC, DouglasCalora commented on client/components/CovSection.vue
> +      background-position: -440px -90px;
está mt especifico não?

2021-03-10 13:12 UTC, DouglasCalora commented on client/components/CovSection.vue
> +      height: 400px;
precisa essa altura definida?

2021-03-10 13:12 UTC, DouglasCalora commented on client/pages/_states/_index.vue
> +          <cov-grid-cell :breakpoints="{ sm:'10-of-12', col:'3-of-6'}">
espaços incorretos no objeto

2021-03-10 13:12 UTC, DouglasCalora commented on client/pages/_states/_index.vue
> +    display: flex;
já n tem uma classe que faz isto?

2021-03-11 12:55 UTC, RafaelM-DEv commented on client/components/CovSection.vue
> +      background-position: -440px -90px;
Está sim, vou criar uma Prop para Background assim posso passar a url sem problemas.

2021-03-11 12:56 UTC, RafaelM-DEv commented on client/components/CovSection.vue
> +      height: 400px;
Eu defini uma altura para que ficasse mais fiel ao Mockup.

2021-03-11 12:59 UTC, RafaelM-DEv commented on client/pages/_states/_index.vue
> +          <cov-grid-cell :breakpoints="{ sm:'10-of-12', col:'3-of-6'}">
dos breakpoints?

2021-03-11 13:01 UTC, RafaelM-DEv commented on client/pages/_states/_index.vue
> +    display: flex;
sim, alterado para essa classe.

2021-03-11 13:14 UTC, DouglasCalora commented on client/pages/_states/_index.vue
> +          <cov-grid-cell :breakpoints="{ sm:'10-of-12', col:'3-of-6'}">
nos `{}` e nas key.

2021-03-11 13:14 UTC, DouglasCalora commented on client/components/CovSection.vue
> +      background-position: -440px -90px;
digo sobre o background position

2021-03-11 13:21 UTC, DouglasCalora commented on client/components/CovSection.vue
> +      height: 400px;
Tente não usar `height`, pode quebrar em algumas telas, talvez um `min-height` que assim nunca vai quebrar...

2021-03-11 13:22 UTC, DouglasCalora commented on client/pages/_states/_index.vue
> +          <cov-grid-cell :breakpoints="{ sm:'10-of-12', col:'3-of-6'}">
nas `{}` e nas keys

2021-03-11 13:31 UTC, RafaelM-DEv commented on client/components/CovSection.vue
> +      background-position: -440px -90px;
verdade, tem que ser em relação a screen, vou achar outra solução!

2021-03-11 13:32 UTC, RafaelM-DEv commented on client/components/CovSection.vue
> +      height: 400px;
saquei

2021-03-11 14:00 UTC, RafaelM-DEv commented on client/pages/_states/_index.vue
> +          <cov-grid-cell :breakpoints="{ sm:'10-of-12', col:'3-of-6'}">
colocar corretamente os breakpoints, saquei

2021-03-11 14:37 UTC, DouglasCalora approved these changes

2021-03-11 18:41 UTC, DouglasCalora approved these changes

2021-03-11 18:41 UTC, merged