Added shortcuts to the calendar
bildvitta/covid pull request #77
Opened 2021-03-22 20:39 UTC by RafaelM-DEv

2021-03-22 22:04 UTC, DouglasCalora requested changes

2021-03-22 22:04 UTC, DouglasCalora commented on client/components/CovDateFilter.vue
> +      window: {
window é palavra reservada, melhor por outro nome

2021-03-22 22:04 UTC, DouglasCalora commented on client/components/CovDateFilter.vue
> +      shortcuts: [
pq isto está em um data? e esta muito repetitivo, faça mais generico

2021-03-22 22:04 UTC, DouglasCalora commented on client/components/CovDateFilter.vue
> +            <button class="mx-btn mx-btn-text" @click="someDaysBefore(emit, 3)">
pq não loopa?

2021-03-22 22:04 UTC, DouglasCalora commented on client/components/CovDateFilter.vue
> +    someDaysBefore (emit, days) {
este nome esta estranho

2021-03-23 18:27 UTC, RafaelM-DEv commented on client/components/CovDateFilter.vue
> +      shortcuts: [
Feito

2021-03-23 18:27 UTC, RafaelM-DEv commented on client/components/CovDateFilter.vue
> +      window: {
Feito

2021-03-23 18:28 UTC, RafaelM-DEv commented on client/components/CovDateFilter.vue
> +            <button class="mx-btn mx-btn-text" @click="someDaysBefore(emit, 3)">
feito

2021-03-23 18:36 UTC, RafaelM-DEv commented on client/components/CovDateFilter.vue
> +    someDaysBefore (emit, days) {
Feito

2021-03-25 13:08 UTC, DouglasCalora approved these changes

2021-03-25 14:43 UTC, merged